export const emotionConfig = 
{
    "1 star": {"colorHex": "#D3D3D3", "colorName": "Light Gray", "emoji": "😞"},
    "2 stars": {"colorHex": "#F5F5DC", "colorName": "Beige", "emoji": "😐"},
    "nervousness": {"colorHex": "#FFFF99", "colorName": "Light Yellow", "emoji": "😟"},
    "realization": {"colorHex": "#FFFF00", "colorName": "Light Bulb Yellow", "emoji": "🤔"},
    "sadness": {"colorHex": "#87CEEB", "colorName": "Cool Blue", "emoji": "😢"},
    "disapproval": {"colorHex": "#6B8E23", "colorName": "Muted Olive", "emoji": "👎"},
    "annoyance": {"colorHex": "#FF8C00", "colorName": "Irritating Orange", "emoji": "😠"},
    "approval": {"colorHex": "#00FF00", "colorName": "Green Light", "emoji": "👍"},
    "remorse": {"colorHex": "#E6E6FA", "colorName": "Soft Lavender", "emoji": "😔"},
    "curiosity": {"colorHex": "#800080", "colorName": "Inquisitive Purple", "emoji": "🤔"},
    "joy": {"colorHex": "#FFD700", "colorName": "Sunny Yellow", "emoji": "😄"},
    "caring": {"colorHex": "#FF69B4", "colorName": "Warm Pink", "emoji": "❤️"},
    "3 starst": {"colorHex": "#FFC0CB", "colorName": "Blushing Pink", "emoji": "😳"},
    "4 stars": {"colorHex": "#FFA500", "colorName": "Bright Orange", "emoji": "😃"},
    "fear": {"colorHex": "#4B0082", "colorName": "Dark Indigo", "emoji": "😨"},
    "relief": {"colorHex": "#98FB98", "colorName": "Mint Green", "emoji": "😌"},
    "5 stars": {"colorHex": "#FF0000", "colorName": "Romantic Red", "emoji": "❤️"},
    "anger": {"colorHex": "#FF4500", "colorName": "Fiery Red", "emoji": "😡"},
    "admiration": {"colorHex": "#4169E1", "colorName": "Royal Blue", "emoji": "😍"},
    "desire": {"colorHex": "#E32636", "colorName": "Passionate Red", "emoji": "😍"},
    "grief": {"colorHex": "#800080", "colorName": "Deep Purple", "emoji": "😔"},
    "surprise": {"colorHex": "#00FFFF", "colorName": "Electric Blue", "emoji": "😲"},
    "excitement": {"colorHex": "#FFFF00", "colorName": "Energetic Yellow", "emoji": "😃"},
    "disgust": {"colorHex": "#8F9779", "colorName": "Sickly Green", "emoji": "🤢"},
    "gratitude": {"colorHex": "#40E0D0", "colorName": "Thankful Turquoise", "emoji": "🙏"},
    "amusement": {"colorHex": "#FFA500", "colorName": "Playful Orange", "emoji": "😄"},
    "pride": {"colorHex": "#800080", "colorName": "Bold Purple", "emoji": "🦚"}
  }