import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function mainLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
              <nav className="nav"> 

              
              </nav>
    
        {children}
        </body>
    </html>
  );
}
