import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Searchinput from "./components/Searchinput";
const inter = Inter({ subsets: ["latin"] });

 export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function mainLayout({ children }) {
  return (
    <html lang="en">
        <body> 
        <div >
            
          </div>
        <div> {children} </div> 
     </body>
    </html>
  );
}
